name: Update Flight Data Hourly

on:
  schedule:
    - cron: "0 * * * *"  # Exécuter toutes les heures
  workflow_dispatch:  # Permet aussi de lancer manuellement

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download previous database artifact
        uses: actions/download-artifact@v3
        with:
          name: flights-database  # Télécharge l'artefact précédent
          path: flights_data.db

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install selenium pandas

      - name: Run scraping script
        run: python schedule.py  # Exécute le script Python

      - name: Upload SQLite database
        uses: actions/upload-artifact@v3
        with:
          name: flights-database
          path: flights_data.db  # Sauvegarde la base mise à jour
