name: Update Flight Data Hourly

on:
  schedule:
    - cron: "0 * * * *"  # Exécuter toutes les heures
  workflow_dispatch:  # Permet d'exécuter manuellement

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable || true

      - name: Remove default Chromium
        run: sudo apt purge chromium-browser || true

      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium

      - name: Run scraping script
        run: python schedule.py

      - name: Upload SQLite database
        uses: actions/upload-artifact@v3
        with:
          name: flights-database
          path: flights_data.db
