name: Download old flights-database

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  download-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest artifact run id
        run: |
          ARTIFACT_RUN_ID=$(curl -s \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=1" \
            | jq '.artifacts[0].workflow_run.id'
          )
          echo "artifact_run_id=$ARTIFACT_RUN_ID" >> $GITHUB_ENV

      - name: Download flights-database
        uses: actions/download-artifact@v4
        with:
          owner: jiji-krk
          repo: flights-scraper
          run-id: ${{ env.artifact_run_id }}
          name: flights-database
          path: .
          # Nécessaire si votre repo est privé, ou pour un run différent
          github-token: ${{ secrets.GH_PAT }}

      - name: Check file
        run: ls -l flights_data.db
